env:
  es6: true
  node: true
  mocha: true
  jest: true
  browser: true

parser: babel-eslint

extends:
  - eslint:recommended
  - airbnb

parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx : true
  sourceType: module

plugins:
  - react

rules:
  arrow-parens:
    - warn
    - as-needed
  brace-style: off
  comma-dangle:
    - error
    - only-multiline
  consistent-return: off # 总返回value
  eol-last: off
  global-require: off

  # 自定义模块警告
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  import/extensions: off
  linebreak-style: off
  no-bitwise: off #禁用位运算
  no-console: off
  no-plusplus: off
  no-underscore-dangle: off
  no-unused-vars: warn
  no-shadow: off # 命名冲突
  no-trailing-spaces: off # 禁止多余空格
  no-param-reassign: off # 禁止修改传参
  no-unused-expressions: off #  a && b
  max-len: off # 禁止单行超出100字节
  no-restricted-syntax: off # 禁用如 for(in) 等语法
  quotes:
    - error
    - single
  spaced-comment: off
  ### react
  # prop-types警用的类型
  react/forbid-prop-types:
    - 2
    - {'forbid': ['']}
  # 非事件元素获取各类事件
  jsx-a11y/no-static-element-interactions: off
  ###??被删除项
  jsx-a11y/href-no-hash: off
  semi: off

globals:
  document: false
  window: false
  layer: true
  localStorage: true
