env:
  es6: true
  node: true

extends:
  - standard
  - standard-react

parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true

# plugins:

rules:
  # 常规
  eol-last: off # 非空文件必需有空行
  space-before-function-paren: off # 函数名后，不强制跟空格
  no-unused-vars: warn # 变量未使用

  # JSX 规则
  jsx-quotes: # jsx属性必需双引号
    - error
    - prefer-double
  react/self-closing-comp:
    - error
    -
      component: true


globals:
  store: true
  window: false
