env:
  es6: true
  node: true
  mocha: true
  jest: true

extends:
  - eslint:recommended
  - airbnb

parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx : true
  sourceType: module

plugins:
  - react

rules:
  comma-dangle:
    - error
    - only-multiline
  import/no-unresolved: off
  linebreak-style: off
  no-console: off
  no-underscore-dangle: off
  no-unused-vars: warn
  quotes:
    - error
    - single
  react/jsx-uses-vars: warn
  jsx-a11y/no-static-element-interactions: warn
  semi:
    - error
    - always

globals:
  document: false
  window: false
  fetch: true