parser: postcss-scss
syntax: postcss-scss
plugins:
  # sass规则：https://github.com/jonathantneal/precss
  precss:
  cssnano:
    preset:
      - advanced
      -
        autoprefixer:
          add: ture
        zindex: false
        normalizeUrl: false
        discardComments:
          removeAll: true

#  lost: # 网格布局: https://github.com/peterramsing/lost
# https://github.com/michael-ciniawsky/postcss-load-config
